name = "dasmoticket"
compatibility_date = "2024-05-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "ticketdb"
database_id = "24fd35b4-68ce-4c41-bf9a-548f6cd83fab"
migrations_dir = "migrations"
